package ca.bc.gov.educ.graddatacollection.api.rules.course;

import lombok.Getter;

import java.util.Arrays;
import java.util.Optional;

@Getter
public enum CourseValidationRulesDependencyMatrix {
    ENTRY1("C02", new String[]{CourseStudentValidationIssueTypeCode.DEM_DATA_MISSING.getCode()}),
    ENTRY2("C03", new String[]{CourseStudentValidationIssueTypeCode.DEM_DATA_MISSING.getCode(), CourseStudentValidationIssueTypeCode.DEM_ISSUE.getCode()}),
    ENTRY3("C04", new String[]{CourseStudentValidationIssueTypeCode.DEM_DATA_MISSING.getCode(), CourseStudentValidationIssueTypeCode.DEM_ISSUE.getCode(), CourseStudentValidationIssueTypeCode.COURSE_CODE_COREG_TRAX_INVALID.getCode(), CourseStudentValidationIssueTypeCode.COURSE_CODE_COREG_MYEDBC_INVALID.getCode(), CourseStudentValidationIssueTypeCode.COURSE_CODE_COREG_TRAX_INVALID.getCode()}),
    ENTRY4("C05", new String[]{CourseStudentValidationIssueTypeCode.DEM_DATA_MISSING.getCode(), CourseStudentValidationIssueTypeCode.DEM_ISSUE.getCode(), CourseStudentValidationIssueTypeCode.COURSE_CODE_COREG_TRAX_INVALID.getCode(), CourseStudentValidationIssueTypeCode.COURSE_CODE_COREG_MYEDBC_INVALID.getCode(), CourseStudentValidationIssueTypeCode.COURSE_CODE_COREG_TRAX_INVALID.getCode()}),
    ENTRY5("C06", new String[]{CourseStudentValidationIssueTypeCode.DEM_DATA_MISSING.getCode(), CourseStudentValidationIssueTypeCode.DEM_ISSUE.getCode(), CourseStudentValidationIssueTypeCode.COURSE_CODE_COREG_TRAX_INVALID.getCode(), CourseStudentValidationIssueTypeCode.COURSE_CODE_COREG_MYEDBC_INVALID.getCode(), CourseStudentValidationIssueTypeCode.COURSE_CODE_COREG_TRAX_INVALID.getCode()}),
    ENTRY6("C07", new String[]{CourseStudentValidationIssueTypeCode.DEM_DATA_MISSING.getCode(), CourseStudentValidationIssueTypeCode.DEM_ISSUE.getCode(), CourseStudentValidationIssueTypeCode.COURSE_CODE_COREG_TRAX_INVALID.getCode(), CourseStudentValidationIssueTypeCode.COURSE_CODE_COREG_MYEDBC_INVALID.getCode(), CourseStudentValidationIssueTypeCode.COURSE_CODE_COREG_TRAX_INVALID.getCode()}),
    ENTRY7("C08", new String[]{CourseStudentValidationIssueTypeCode.DEM_DATA_MISSING.getCode(), CourseStudentValidationIssueTypeCode.DEM_ISSUE.getCode(), CourseStudentValidationIssueTypeCode.COURSE_CODE_COREG_TRAX_INVALID.getCode(), CourseStudentValidationIssueTypeCode.COURSE_CODE_COREG_MYEDBC_INVALID.getCode(), CourseStudentValidationIssueTypeCode.COURSE_CODE_COREG_TRAX_INVALID.getCode()}),
    ENTRY8("C09", new String[]{CourseStudentValidationIssueTypeCode.DEM_DATA_MISSING.getCode(), CourseStudentValidationIssueTypeCode.DEM_ISSUE.getCode(), CourseStudentValidationIssueTypeCode.COURSE_CODE_COREG_TRAX_INVALID.getCode(), CourseStudentValidationIssueTypeCode.COURSE_CODE_COREG_MYEDBC_INVALID.getCode(), CourseStudentValidationIssueTypeCode.COURSE_CODE_COREG_TRAX_INVALID.getCode()}),
    ENTRY9("C10", new String[]{CourseStudentValidationIssueTypeCode.DEM_DATA_MISSING.getCode(), CourseStudentValidationIssueTypeCode.DEM_ISSUE.getCode(), CourseStudentValidationIssueTypeCode.COURSE_CODE_COREG_TRAX_INVALID.getCode(), CourseStudentValidationIssueTypeCode.COURSE_CODE_COREG_MYEDBC_INVALID.getCode(), CourseStudentValidationIssueTypeCode.COURSE_CODE_COREG_TRAX_INVALID.getCode()}),
    ENTRY10("C11", new String[]{CourseStudentValidationIssueTypeCode.DEM_DATA_MISSING.getCode(), CourseStudentValidationIssueTypeCode.DEM_ISSUE.getCode(), CourseStudentValidationIssueTypeCode.COURSE_CODE_COREG_TRAX_INVALID.getCode(), CourseStudentValidationIssueTypeCode.COURSE_CODE_COREG_MYEDBC_INVALID.getCode(), CourseStudentValidationIssueTypeCode.COURSE_CODE_COREG_TRAX_INVALID.getCode(), CourseStudentValidationIssueTypeCode.COURSE_STATUS_INVALID.getCode()}),
    ENTRY11("C12", new String[]{CourseStudentValidationIssueTypeCode.DEM_DATA_MISSING.getCode(), CourseStudentValidationIssueTypeCode.DEM_ISSUE.getCode(), CourseStudentValidationIssueTypeCode.COURSE_CODE_COREG_TRAX_INVALID.getCode(), CourseStudentValidationIssueTypeCode.COURSE_CODE_COREG_MYEDBC_INVALID.getCode(), CourseStudentValidationIssueTypeCode.COURSE_CODE_COREG_TRAX_INVALID.getCode(), CourseStudentValidationIssueTypeCode.COURSE_STATUS_INVALID.getCode()}),
    ENTRY12("C13", new String[]{CourseStudentValidationIssueTypeCode.DEM_DATA_MISSING.getCode(), CourseStudentValidationIssueTypeCode.DEM_ISSUE.getCode(), CourseStudentValidationIssueTypeCode.COURSE_MONTH_INVALID.getCode(), CourseStudentValidationIssueTypeCode.COURSE_YEAR_INVALID.getCode(), CourseStudentValidationIssueTypeCode.COURSE_CODE_COREG_TRAX_INVALID.getCode(), CourseStudentValidationIssueTypeCode.COURSE_CODE_COREG_MYEDBC_INVALID.getCode(), CourseStudentValidationIssueTypeCode.COURSE_CODE_COREG_TRAX_INVALID.getCode()}),
    ENTRY13("C14", new String[]{CourseStudentValidationIssueTypeCode.DEM_DATA_MISSING.getCode(), CourseStudentValidationIssueTypeCode.DEM_ISSUE.getCode(), CourseStudentValidationIssueTypeCode.COURSE_MONTH_INVALID.getCode(), CourseStudentValidationIssueTypeCode.COURSE_YEAR_INVALID.getCode(), CourseStudentValidationIssueTypeCode.COURSE_CODE_COREG_TRAX_INVALID.getCode(), CourseStudentValidationIssueTypeCode.COURSE_CODE_COREG_MYEDBC_INVALID.getCode(), CourseStudentValidationIssueTypeCode.COURSE_CODE_COREG_TRAX_INVALID.getCode()}),
    ENTRY14("C15", new String[]{CourseStudentValidationIssueTypeCode.DEM_DATA_MISSING.getCode(), CourseStudentValidationIssueTypeCode.DEM_ISSUE.getCode(), CourseStudentValidationIssueTypeCode.COURSE_MONTH_INVALID.getCode(), CourseStudentValidationIssueTypeCode.COURSE_YEAR_INVALID.getCode(), CourseStudentValidationIssueTypeCode.COURSE_CODE_COREG_TRAX_INVALID.getCode(), CourseStudentValidationIssueTypeCode.COURSE_CODE_COREG_MYEDBC_INVALID.getCode(), CourseStudentValidationIssueTypeCode.COURSE_CODE_COREG_TRAX_INVALID.getCode()}),
    ENTRY15("C16", new String[]{CourseStudentValidationIssueTypeCode.DEM_DATA_MISSING.getCode(), CourseStudentValidationIssueTypeCode.DEM_ISSUE.getCode(), CourseStudentValidationIssueTypeCode.COURSE_MONTH_INVALID.getCode(), CourseStudentValidationIssueTypeCode.COURSE_YEAR_INVALID.getCode(), CourseStudentValidationIssueTypeCode.COURSE_CODE_COREG_TRAX_INVALID.getCode(), CourseStudentValidationIssueTypeCode.COURSE_CODE_COREG_MYEDBC_INVALID.getCode(), CourseStudentValidationIssueTypeCode.COURSE_CODE_COREG_TRAX_INVALID.getCode()}),
    ENTRY16("C17", new String[]{CourseStudentValidationIssueTypeCode.DEM_DATA_MISSING.getCode(), CourseStudentValidationIssueTypeCode.DEM_ISSUE.getCode(), CourseStudentValidationIssueTypeCode.COURSE_CODE_COREG_TRAX_INVALID.getCode(), CourseStudentValidationIssueTypeCode.COURSE_CODE_COREG_MYEDBC_INVALID.getCode(), CourseStudentValidationIssueTypeCode.COURSE_CODE_COREG_TRAX_INVALID.getCode(), CourseStudentValidationIssueTypeCode.INVALID_FINE_ARTS_APPLIED_SKILLS_CODE.getCode()}),
    ENTRY17("C18", new String[]{CourseStudentValidationIssueTypeCode.DEM_DATA_MISSING.getCode(), CourseStudentValidationIssueTypeCode.DEM_ISSUE.getCode(), CourseStudentValidationIssueTypeCode.COURSE_MONTH_INVALID.getCode(), CourseStudentValidationIssueTypeCode.COURSE_YEAR_INVALID.getCode(), CourseStudentValidationIssueTypeCode.COURSE_CODE_COREG_TRAX_INVALID.getCode(), CourseStudentValidationIssueTypeCode.COURSE_CODE_COREG_MYEDBC_INVALID.getCode(), CourseStudentValidationIssueTypeCode.COURSE_CODE_COREG_TRAX_INVALID.getCode(), CourseStudentValidationIssueTypeCode.COURSE_SESSION_INVALID.getCode()}),
    ENTRY18("C19", new String[]{CourseStudentValidationIssueTypeCode.DEM_DATA_MISSING.getCode(), CourseStudentValidationIssueTypeCode.DEM_ISSUE.getCode(), CourseStudentValidationIssueTypeCode.COURSE_MONTH_INVALID.getCode(), CourseStudentValidationIssueTypeCode.COURSE_YEAR_INVALID.getCode(), CourseStudentValidationIssueTypeCode.COURSE_CODE_COREG_TRAX_INVALID.getCode(), CourseStudentValidationIssueTypeCode.COURSE_CODE_COREG_MYEDBC_INVALID.getCode(), CourseStudentValidationIssueTypeCode.COURSE_CODE_COREG_TRAX_INVALID.getCode(), CourseStudentValidationIssueTypeCode.COURSE_SESSION_INVALID.getCode()}),
    ENTRY19("C20", new String[]{CourseStudentValidationIssueTypeCode.DEM_DATA_MISSING.getCode(), CourseStudentValidationIssueTypeCode.DEM_ISSUE.getCode(), CourseStudentValidationIssueTypeCode.COURSE_MONTH_INVALID.getCode(), CourseStudentValidationIssueTypeCode.COURSE_YEAR_INVALID.getCode(), CourseStudentValidationIssueTypeCode.COURSE_CODE_COREG_TRAX_INVALID.getCode(), CourseStudentValidationIssueTypeCode.COURSE_CODE_COREG_MYEDBC_INVALID.getCode(), CourseStudentValidationIssueTypeCode.COURSE_CODE_COREG_TRAX_INVALID.getCode(), CourseStudentValidationIssueTypeCode.COURSE_SESSION_INVALID.getCode()}),
    ENTRY20("C21", new String[]{CourseStudentValidationIssueTypeCode.DEM_DATA_MISSING.getCode(), CourseStudentValidationIssueTypeCode.DEM_ISSUE.getCode(), CourseStudentValidationIssueTypeCode.COURSE_MONTH_INVALID.getCode(), CourseStudentValidationIssueTypeCode.COURSE_YEAR_INVALID.getCode(), CourseStudentValidationIssueTypeCode.COURSE_CODE_COREG_TRAX_INVALID.getCode(), CourseStudentValidationIssueTypeCode.COURSE_CODE_COREG_MYEDBC_INVALID.getCode(), CourseStudentValidationIssueTypeCode.COURSE_CODE_COREG_TRAX_INVALID.getCode(), CourseStudentValidationIssueTypeCode.COURSE_SESSION_INVALID.getCode()}),
    ENTRY21("C22", new String[]{CourseStudentValidationIssueTypeCode.DEM_DATA_MISSING.getCode(), CourseStudentValidationIssueTypeCode.DEM_ISSUE.getCode(), CourseStudentValidationIssueTypeCode.COURSE_MONTH_INVALID.getCode(), CourseStudentValidationIssueTypeCode.COURSE_YEAR_INVALID.getCode(), CourseStudentValidationIssueTypeCode.COURSE_CODE_COREG_TRAX_INVALID.getCode(), CourseStudentValidationIssueTypeCode.COURSE_CODE_COREG_MYEDBC_INVALID.getCode(), CourseStudentValidationIssueTypeCode.COURSE_CODE_COREG_TRAX_INVALID.getCode(), CourseStudentValidationIssueTypeCode.COURSE_SESSION_INVALID.getCode()}),
    ENTRY22("C23", new String[]{CourseStudentValidationIssueTypeCode.DEM_DATA_MISSING.getCode(), CourseStudentValidationIssueTypeCode.DEM_ISSUE.getCode(), CourseStudentValidationIssueTypeCode.COURSE_MONTH_INVALID.getCode(), CourseStudentValidationIssueTypeCode.COURSE_YEAR_INVALID.getCode(), CourseStudentValidationIssueTypeCode.COURSE_CODE_COREG_TRAX_INVALID.getCode(), CourseStudentValidationIssueTypeCode.COURSE_CODE_COREG_MYEDBC_INVALID.getCode(), CourseStudentValidationIssueTypeCode.COURSE_CODE_COREG_TRAX_INVALID.getCode(), CourseStudentValidationIssueTypeCode.COURSE_SESSION_INVALID.getCode()}),
    ENTRY23("C24", new String[]{CourseStudentValidationIssueTypeCode.DEM_DATA_MISSING.getCode(), CourseStudentValidationIssueTypeCode.DEM_ISSUE.getCode(), CourseStudentValidationIssueTypeCode.COURSE_MONTH_INVALID.getCode(), CourseStudentValidationIssueTypeCode.COURSE_YEAR_INVALID.getCode(), CourseStudentValidationIssueTypeCode.COURSE_CODE_COREG_TRAX_INVALID.getCode(), CourseStudentValidationIssueTypeCode.COURSE_CODE_COREG_MYEDBC_INVALID.getCode(), CourseStudentValidationIssueTypeCode.COURSE_CODE_COREG_TRAX_INVALID.getCode(), CourseStudentValidationIssueTypeCode.COURSE_SESSION_INVALID.getCode()}),
    ENTRY24("C25", new String[]{CourseStudentValidationIssueTypeCode.DEM_DATA_MISSING.getCode(), CourseStudentValidationIssueTypeCode.DEM_ISSUE.getCode(), CourseStudentValidationIssueTypeCode.COURSE_MONTH_INVALID.getCode(), CourseStudentValidationIssueTypeCode.COURSE_YEAR_INVALID.getCode(), CourseStudentValidationIssueTypeCode.COURSE_CODE_COREG_TRAX_INVALID.getCode(), CourseStudentValidationIssueTypeCode.COURSE_CODE_COREG_MYEDBC_INVALID.getCode(), CourseStudentValidationIssueTypeCode.COURSE_CODE_COREG_TRAX_INVALID.getCode(), CourseStudentValidationIssueTypeCode.COURSE_SESSION_INVALID.getCode()}),
    ENTRY25("C26", new String[]{CourseStudentValidationIssueTypeCode.DEM_DATA_MISSING.getCode(), CourseStudentValidationIssueTypeCode.DEM_ISSUE.getCode(), CourseStudentValidationIssueTypeCode.COURSE_MONTH_INVALID.getCode(), CourseStudentValidationIssueTypeCode.COURSE_YEAR_INVALID.getCode(), CourseStudentValidationIssueTypeCode.COURSE_CODE_COREG_TRAX_INVALID.getCode(), CourseStudentValidationIssueTypeCode.COURSE_CODE_COREG_MYEDBC_INVALID.getCode(), CourseStudentValidationIssueTypeCode.COURSE_CODE_COREG_TRAX_INVALID.getCode(), CourseStudentValidationIssueTypeCode.COURSE_SESSION_INVALID.getCode(), CourseStudentValidationIssueTypeCode.INVALID_FINE_ARTS_APPLIED_SKILLS_CODE.getCode()}),
    ENTRY26("C27", new String[]{CourseStudentValidationIssueTypeCode.DEM_DATA_MISSING.getCode(), CourseStudentValidationIssueTypeCode.DEM_ISSUE.getCode(), CourseStudentValidationIssueTypeCode.COURSE_MONTH_INVALID.getCode(), CourseStudentValidationIssueTypeCode.COURSE_YEAR_INVALID.getCode(), CourseStudentValidationIssueTypeCode.COURSE_CODE_COREG_TRAX_INVALID.getCode(), CourseStudentValidationIssueTypeCode.COURSE_CODE_COREG_MYEDBC_INVALID.getCode(), CourseStudentValidationIssueTypeCode.COURSE_CODE_COREG_TRAX_INVALID.getCode(), CourseStudentValidationIssueTypeCode.COURSE_SESSION_INVALID.getCode(), CourseStudentValidationIssueTypeCode.INVALID_FINE_ARTS_APPLIED_SKILLS_CODE.getCode()}),
    ENTRY27("C28", new String[]{CourseStudentValidationIssueTypeCode.DEM_DATA_MISSING.getCode(), CourseStudentValidationIssueTypeCode.DEM_ISSUE.getCode(), CourseStudentValidationIssueTypeCode.COURSE_NOT_INDEPENDENT_DIRECTED_STUDIES.getCode(), CourseStudentValidationIssueTypeCode.RELATED_COURSE_RELATED_LEVEL_MISSING_FOR_INDY.getCode(), CourseStudentValidationIssueTypeCode.COURSE_CODE_COREG_TRAX_INVALID.getCode(), CourseStudentValidationIssueTypeCode.COURSE_CODE_COREG_MYEDBC_INVALID.getCode(), CourseStudentValidationIssueTypeCode.COURSE_CODE_COREG_TRAX_INVALID.getCode()}),
    ENTRY28("C29", new String[]{CourseStudentValidationIssueTypeCode.DEM_DATA_MISSING.getCode(), CourseStudentValidationIssueTypeCode.DEM_ISSUE.getCode(), CourseStudentValidationIssueTypeCode.INTERIM_PCT_INVALID.getCode(), CourseStudentValidationIssueTypeCode.INTERIM_LETTER_GRADE_INVALID.getCode(), CourseStudentValidationIssueTypeCode.COURSE_CODE_COREG_TRAX_INVALID.getCode(), CourseStudentValidationIssueTypeCode.COURSE_CODE_COREG_MYEDBC_INVALID.getCode(), CourseStudentValidationIssueTypeCode.COURSE_CODE_COREG_TRAX_INVALID.getCode()}),
    ENTRY29("C30", new String[]{CourseStudentValidationIssueTypeCode.DEM_DATA_MISSING.getCode(), CourseStudentValidationIssueTypeCode.DEM_ISSUE.getCode(), CourseStudentValidationIssueTypeCode.FINAL_LETTER_GRADE_OR_PERCENT_NOT_BLANK.getCode(), CourseStudentValidationIssueTypeCode.COURSE_CODE_COREG_TRAX_INVALID.getCode(), CourseStudentValidationIssueTypeCode.COURSE_CODE_COREG_MYEDBC_INVALID.getCode(), CourseStudentValidationIssueTypeCode.COURSE_CODE_COREG_TRAX_INVALID.getCode(), CourseStudentValidationIssueTypeCode.COURSE_MONTH_INVALID.getCode(), CourseStudentValidationIssueTypeCode.COURSE_YEAR_INVALID.getCode(), CourseStudentValidationIssueTypeCode.COURSE_SESSION_INVALID.getCode()}),
    ENTRY30("C31", new String[]{CourseStudentValidationIssueTypeCode.DEM_DATA_MISSING.getCode(), CourseStudentValidationIssueTypeCode.DEM_ISSUE.getCode(), CourseStudentValidationIssueTypeCode.FINAL_LETTER_GRADE_OR_PERCENT_NOT_BLANK.getCode(), CourseStudentValidationIssueTypeCode.COURSE_CODE_COREG_TRAX_INVALID.getCode(), CourseStudentValidationIssueTypeCode.COURSE_CODE_COREG_MYEDBC_INVALID.getCode(), CourseStudentValidationIssueTypeCode.COURSE_CODE_COREG_TRAX_INVALID.getCode(), CourseStudentValidationIssueTypeCode.COURSE_MONTH_INVALID.getCode(), CourseStudentValidationIssueTypeCode.COURSE_YEAR_INVALID.getCode(), CourseStudentValidationIssueTypeCode.COURSE_SESSION_INVALID.getCode()}),
    ENTRY31("C32", new String[]{CourseStudentValidationIssueTypeCode.DEM_DATA_MISSING.getCode(), CourseStudentValidationIssueTypeCode.DEM_ISSUE.getCode(), CourseStudentValidationIssueTypeCode.FINAL_LETTER_GRADE_OR_PERCENT_NOT_BLANK.getCode(), CourseStudentValidationIssueTypeCode.COURSE_CODE_COREG_TRAX_INVALID.getCode(), CourseStudentValidationIssueTypeCode.COURSE_CODE_COREG_MYEDBC_INVALID.getCode(), CourseStudentValidationIssueTypeCode.COURSE_CODE_COREG_TRAX_INVALID.getCode(), CourseStudentValidationIssueTypeCode.COURSE_MONTH_INVALID.getCode(), CourseStudentValidationIssueTypeCode.COURSE_YEAR_INVALID.getCode(), CourseStudentValidationIssueTypeCode.COURSE_SESSION_INVALID.getCode()}),
    ENTRY32("C33", new String[]{CourseStudentValidationIssueTypeCode.DEM_DATA_MISSING.getCode(), CourseStudentValidationIssueTypeCode.DEM_ISSUE.getCode(), CourseStudentValidationIssueTypeCode.INVALID_FINE_ARTS_APPLIED_SKILLS_CODE.getCode(), CourseStudentValidationIssueTypeCode.COURSE_SESSION_INVALID.getCode(), CourseStudentValidationIssueTypeCode.COURSE_CODE_COREG_TRAX_INVALID.getCode(),CourseStudentValidationIssueTypeCode.COURSE_MONTH_INVALID.getCode(), CourseStudentValidationIssueTypeCode.COURSE_YEAR_INVALID.getCode(), CourseStudentValidationIssueTypeCode.COURSE_CODE_COREG_MYEDBC_INVALID.getCode(), CourseStudentValidationIssueTypeCode.COURSE_CODE_COREG_TRAX_INVALID.getCode()}),
    ENTRY33("C34", new String[]{CourseStudentValidationIssueTypeCode.DEM_DATA_MISSING.getCode(), CourseStudentValidationIssueTypeCode.DEM_ISSUE.getCode(),CourseStudentValidationIssueTypeCode.COURSE_MONTH_INVALID.getCode(), CourseStudentValidationIssueTypeCode.COURSE_YEAR_INVALID.getCode(), CourseStudentValidationIssueTypeCode.COURSE_STATUS_INVALID.getCode(), CourseStudentValidationIssueTypeCode.COURSE_CODE_COREG_TRAX_INVALID.getCode(), CourseStudentValidationIssueTypeCode.COURSE_CODE_COREG_MYEDBC_INVALID.getCode(), CourseStudentValidationIssueTypeCode.COURSE_CODE_COREG_TRAX_INVALID.getCode()}),
    ENTRY34("C35", new String[]{CourseStudentValidationIssueTypeCode.DEM_DATA_MISSING.getCode(), CourseStudentValidationIssueTypeCode.DEM_ISSUE.getCode(), CourseStudentValidationIssueTypeCode.FINAL_LETTER_GRADE_INVALID.getCode(), CourseStudentValidationIssueTypeCode.FINAL_LETTER_GRADE_OR_PERCENT_NOT_BLANK.getCode(), CourseStudentValidationIssueTypeCode.COURSE_CODE_COREG_TRAX_INVALID.getCode(), CourseStudentValidationIssueTypeCode.COURSE_CODE_COREG_MYEDBC_INVALID.getCode(), CourseStudentValidationIssueTypeCode.COURSE_CODE_COREG_TRAX_INVALID.getCode(), CourseStudentValidationIssueTypeCode.COURSE_MONTH_INVALID.getCode(), CourseStudentValidationIssueTypeCode.COURSE_YEAR_INVALID.getCode(), CourseStudentValidationIssueTypeCode.COURSE_SESSION_INVALID.getCode()}),
    ENTRY35("C36", new String[]{CourseStudentValidationIssueTypeCode.DEM_DATA_MISSING.getCode(), CourseStudentValidationIssueTypeCode.DEM_ISSUE.getCode(), CourseStudentValidationIssueTypeCode.FINAL_LETTER_GRADE_INVALID.getCode(), CourseStudentValidationIssueTypeCode.FINAL_LETTER_GRADE_OR_PERCENT_NOT_BLANK.getCode(), CourseStudentValidationIssueTypeCode.COURSE_CODE_COREG_TRAX_INVALID.getCode(), CourseStudentValidationIssueTypeCode.COURSE_CODE_COREG_MYEDBC_INVALID.getCode(), CourseStudentValidationIssueTypeCode.COURSE_CODE_COREG_TRAX_INVALID.getCode(), CourseStudentValidationIssueTypeCode.COURSE_MONTH_INVALID.getCode(), CourseStudentValidationIssueTypeCode.COURSE_YEAR_INVALID.getCode(), CourseStudentValidationIssueTypeCode.COURSE_SESSION_INVALID.getCode()}),
    ENTRY36("C37", new String[]{CourseStudentValidationIssueTypeCode.DEM_DATA_MISSING.getCode(), CourseStudentValidationIssueTypeCode.DEM_ISSUE.getCode(), CourseStudentValidationIssueTypeCode.FINAL_LETTER_GRADE_INVALID.getCode(), CourseStudentValidationIssueTypeCode.FINAL_PCT_NOT_BLANK.getCode(), CourseStudentValidationIssueTypeCode.FINAL_PCT_INVALID.getCode(), CourseStudentValidationIssueTypeCode.FINAL_LETTER_GRADE_OR_PERCENT_NOT_BLANK.getCode(), CourseStudentValidationIssueTypeCode.COURSE_CODE_COREG_TRAX_INVALID.getCode(), CourseStudentValidationIssueTypeCode.COURSE_CODE_COREG_MYEDBC_INVALID.getCode(), CourseStudentValidationIssueTypeCode.COURSE_CODE_COREG_TRAX_INVALID.getCode(), CourseStudentValidationIssueTypeCode.COURSE_MONTH_INVALID.getCode(), CourseStudentValidationIssueTypeCode.COURSE_YEAR_INVALID.getCode(), CourseStudentValidationIssueTypeCode.COURSE_SESSION_INVALID.getCode()}),
    ENTRY37("C38", new String[]{CourseStudentValidationIssueTypeCode.DEM_DATA_MISSING.getCode(), CourseStudentValidationIssueTypeCode.DEM_ISSUE.getCode(), CourseStudentValidationIssueTypeCode.FINAL_LETTER_GRADE_INVALID.getCode(), CourseStudentValidationIssueTypeCode.FINAL_LETTER_GRADE_OR_PERCENT_NOT_BLANK.getCode(), CourseStudentValidationIssueTypeCode.COURSE_CODE_COREG_TRAX_INVALID.getCode(), CourseStudentValidationIssueTypeCode.COURSE_CODE_COREG_MYEDBC_INVALID.getCode(), CourseStudentValidationIssueTypeCode.COURSE_CODE_COREG_TRAX_INVALID.getCode(), CourseStudentValidationIssueTypeCode.COURSE_MONTH_INVALID.getCode(), CourseStudentValidationIssueTypeCode.COURSE_YEAR_INVALID.getCode(), CourseStudentValidationIssueTypeCode.COURSE_SESSION_INVALID.getCode()}),
    ENTRY38("C39", new String[]{CourseStudentValidationIssueTypeCode.DEM_DATA_MISSING.getCode(), CourseStudentValidationIssueTypeCode.DEM_ISSUE.getCode(), CourseStudentValidationIssueTypeCode.FINAL_LETTER_GRADE_INVALID.getCode(), CourseStudentValidationIssueTypeCode.FINAL_LETTER_GRADE_OR_PERCENT_NOT_BLANK.getCode(), CourseStudentValidationIssueTypeCode.COURSE_CODE_COREG_TRAX_INVALID.getCode(), CourseStudentValidationIssueTypeCode.COURSE_CODE_COREG_MYEDBC_INVALID.getCode(), CourseStudentValidationIssueTypeCode.COURSE_CODE_COREG_TRAX_INVALID.getCode(), CourseStudentValidationIssueTypeCode.COURSE_MONTH_INVALID.getCode(), CourseStudentValidationIssueTypeCode.COURSE_YEAR_INVALID.getCode(), CourseStudentValidationIssueTypeCode.COURSE_SESSION_INVALID.getCode()}),
    ENTRY39("C40", new String[]{CourseStudentValidationIssueTypeCode.DEM_DATA_MISSING.getCode(), CourseStudentValidationIssueTypeCode.DEM_ISSUE.getCode(), CourseStudentValidationIssueTypeCode.FINAL_LETTER_GRADE_INVALID.getCode(), CourseStudentValidationIssueTypeCode.FINAL_LETTER_GRADE_OR_PERCENT_NOT_BLANK.getCode(), CourseStudentValidationIssueTypeCode.COURSE_CODE_COREG_TRAX_INVALID.getCode(), CourseStudentValidationIssueTypeCode.COURSE_CODE_COREG_MYEDBC_INVALID.getCode(), CourseStudentValidationIssueTypeCode.COURSE_CODE_COREG_TRAX_INVALID.getCode(), CourseStudentValidationIssueTypeCode.COURSE_MONTH_INVALID.getCode(), CourseStudentValidationIssueTypeCode.COURSE_YEAR_INVALID.getCode(), CourseStudentValidationIssueTypeCode.COURSE_SESSION_INVALID.getCode()}),

    ;

    private final String ruleID;
    private final String[] baseRuleErrorCode;
    CourseValidationRulesDependencyMatrix(String ruleID, String[] baseRuleErrorCode) {
        this.ruleID = ruleID;
        this.baseRuleErrorCode = baseRuleErrorCode;
    }

    public static Optional<CourseValidationRulesDependencyMatrix> findByValue(String ruleID) {
        return Arrays.stream(values()).filter(code -> code.ruleID.equalsIgnoreCase(ruleID)).findFirst();
    }
}
