ALTER TABLE DEMOGRAPHIC_STUDENT_VALIDATION_ISSUE
    ALTER COLUMN VALIDATION_ISSUE_DESCRIPTION SET NOT NULL;

ALTER TABLE COURSE_STUDENT_VALIDATION_ISSUE
    ALTER COLUMN VALIDATION_ISSUE_DESCRIPTION SET NOT NULL;

ALTER TABLE ASSESSMENT_STUDENT_VALIDATION_ISSUE
    ALTER COLUMN VALIDATION_ISSUE_DESCRIPTION SET NOT NULL;
