DELETE FROM STUDENT_STATUS_CODE WHERE STUDENT_STATUS_CODE = 'UPDATED';

INSERT INTO STUDENT_STATUS_CODE (STUDENT_STATUS_CODE, LABEL, DESCRIPTION, DISPLAY_ORDER,
                                 CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
VALUES ('UPDATE_CRS', 'Update Course', 'Update course record downstream', '10',
        'API_GRAD_DATA_COLLECTION',
        TO_DATE('20250530', 'YYYYMMDD'),
        'API_GRAD_DATA_COLLECTION', TO_DATE('20250530', 'YYYYMMDD'));