ALTER TABLE ASSESSMENT_STUDENT
    ADD COLUMN ASSESSMENT_ID UUID;

ALTER TABLE ASSESSMENT_STUDENT
    ADD COLUMN TRANSACTION_ID VARCHAR(3);

ALTER TABLE COURSE_STUDENT
    ADD COLUMN TRANSACTION_ID VARCHAR(3);

ALTER TABLE DEMOGRAPHIC_STUDENT
    ADD COLUMN TRANSACTION_ID VARCHAR(3);
