CREATE TABLE REPORTING_PERIOD
(
    REPORTING_PERIOD_ID UUID      NOT NULL,
    SCH_YR_START      TIMESTAMP NOT NULL,
    SCH_YR_END        TIMESTAMP NOT NULL,
    SUMMER_START      TIMESTAMP NOT NULL,
    SUMMER_END        TIMESTAMP NOT NULL,
    CREATE_USER       VARCHAR(100)                        NOT NULL,
    CREATE_DATE       TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATE_USER       VARCHAR(100)                        NOT NULL,
    UPDATE_DATE       TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT REPORTING_PERIOD_ID_PK PRIMARY KEY (REPORTING_PERIOD_ID)
);

ALTER TABLE INCOMING_FILESET
    ADD COLUMN REPORTING_PERIOD_ID UUID,
    ADD CONSTRAINT FK_REPORTING_PERIOD_ID FOREIGN KEY (REPORTING_PERIOD_ID)
        REFERENCES REPORTING_PERIOD (REPORTING_PERIOD_ID);


ALTER TABLE INCOMING_FILESET
    ALTER COLUMN REPORTING_PERIOD_ID SET NOT NULL;
