ALTER TABLE ASSESSMENT_STUDENT
    ADD COLUMN VENDOR_ID VARCHAR(1);

ALTER TABLE COURSE_STUDENT
    ADD COLUMN VENDOR_ID VARCHAR(1);

ALTER TABLE DEMOGRAPHIC_STUDENT
    ADD COLUMN VENDOR_ID VARCHAR(1);
