CREATE TABLE REPORTING_PERIOD
(
    REPORTING_PERIOD_ID                  UUID                                NOT NULL,
    SCH_YR_START                         TIMESTAMP                           NOT NULL,
    SCH_YR_END                           TIMESTAMP                           NOT NULL,
    SUMMER_START                         TIMESTAMP                           NOT NULL,
    SUMMER_END                           TIMESTAMP                           NOT NULL,
    CREATE_USER                          VARCHAR(100)                        NOT NULL,
    CREATE_DATE                          TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATE_USER                          VARCHAR(100)                        NOT NULL,
    UPDATE_DATE                          TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT REPORTING_PERIOD_ID_PK (REPORTING_PERIOD_ID)
);

INSERT INTO REPORTING_PERIOD (SCH_YR_START, SCH_YR_END, SUMMER_START, SUMMER_END, CREATE_USER, UPDATE_USER)
VALUES
    (TO_DATE('20241007', 'YYYYMMDD'), TO_DATE('20250718', 'YYYYMMDD'),
     TO_DATE('20250818', 'YYYYMMDD'), TO_DATE('20250912', 'YYYYMMDD'),
     'API_GRAD_DATA_COLLECTION', 'API_GRAD_DATA_COLLECTION'),
    (TO_DATE('20231002', 'YYYYMMDD'), TO_DATE('20240719', 'YYYYMMDD'),
     TO_DATE('20240819', 'YYYYMMDD'), TO_DATE('20240913', 'YYYYMMDD'),
     'API_GRAD_DATA_COLLECTION', 'API_GRAD_DATA_COLLECTION'),
    (TO_DATE('20221003', 'YYYYMMDD'), TO_DATE('20230721', 'YYYYMMDD'),
     TO_DATE('20230821', 'YYYYMMDD'), TO_DATE('20230908', 'YYYYMMDD'),
     'API_GRAD_DATA_COLLECTION', 'API_GRAD_DATA_COLLECTION');

ALTER TABLE INCOMING_FILESET
    ADD COLUMN REPORTING_PERIOD_ID UUID,
    ADD CONSTRAINT FK_REPORTING_PERIOD_ID FOREIGN KEY (REPORTING_PERIOD_ID)
        REFERENCES REPORTING_PERIOD (REPORTING_PERIOD_ID);

UPDATE INCOMING_FILESET SET REPORTING_PERIOD_ID = (SELECT R.REPORTING_PERIOD_ID FROM REPORTING_PERIOD R WHERE R.SCH_YR_START > TO_DATE('20241006', 'YYYYMMDD') AND R.SUMMER_END < TO_DATE('20250911', 'YYYMMDD'))
    WHERE CREATE_DATE > TO_DATE('20241006', 'YYYYMMDD') AND CREATE_DATE < TO_DATE('20250911', 'YYYYMMDD');

UPDATE INCOMING_FILESET SET REPORTING_PERIOD_ID = (SELECT R.REPORTING_PERIOD_ID FROM REPORTING_PERIOD R WHERE R.SCH_YR_START > TO_DATE('20231001', 'YYYYMMDD') AND R.SUMMER_END < TO_DATE('20240912', 'YYYMMDD'))
    WHERE CREATE_DATE > TO_DATE('20231001', 'YYYYMMDD') AND CREATE_DATE < TO_DATE('20240912', 'YYYYMMDD');

UPDATE INCOMING_FILESET SET REPORTING_PERIOD_ID = (SELECT R.REPORTING_PERIOD_ID FROM REPORTING_PERIOD R WHERE R.SCH_YR_START > TO_DATE('20221002', 'YYYYMMDD') AND R.SUMMER_END < TO_DATE('20230907', 'YYYMMDD'))
    WHERE CREATE_DATE > TO_DATE('20221002', 'YYYYMMDD') AND CREATE_DATE < TO_DATE('20230907', 'YYYYMMDD');

ALTER TABLE INCOMING_FILESET ALTER COLUMN REPORTING_PERIOD_ID SET NOT NULL;