ALTER TABLE INCOMING_FILESET
    ADD COLUMN DISTRICT_ID UUID;

CREATE INDEX FILESET_DISTRICT_ID_IDX ON INCOMING_FILESET (DISTRICT_ID);
CREATE INDEX FILESET_SCHOOL_ID_IDX ON INCOMING_FILESET (SCHOOL_ID);

CREATE TABLE GRAD_SAGA
(
    SAGA_ID            UUID                                NOT NULL,
    INCOMING_FILESET_ID       UUID,
    DEMOGRAPHIC_STUDENT_ID        UUID,
    ASSESSMENT_STUDENT_ID      UUID,
    COURSE_STUDENT_ID          UUID,
    SAGA_NAME          VARCHAR(50)                         NOT NULL,
    SAGA_STATE         VARCHAR(100)                        NOT NULL,
    PAYLOAD            VARCHAR                             NOT NULL,
    RETRY_COUNT        INTEGER,
    STATUS             VARCHAR(20)                         NOT NULL,
    CREATE_USER        VARCHAR(32)                         NOT NULL,
    CREATE_DATE        TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATE_USER        VARCHAR(32)                         NOT NULL,
    UPDATE_DATE        TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT GRAD_SAGA_PK PRIMARY KEY (SAGA_ID)
);

CREATE INDEX GRAD_SAGA_STATUS_IDX ON GRAD_SAGA (STATUS);
CREATE INDEX INCOMING_FILESET_ID_DEMOGRAPHIC_STUDENT_ID_IDX ON GRAD_SAGA (INCOMING_FILESET_ID, DEMOGRAPHIC_STUDENT_ID);
CREATE INDEX INCOMING_FILESET_ID_ASSESSMENT_STUDENT_ID_IDX ON GRAD_SAGA (INCOMING_FILESET_ID, ASSESSMENT_STUDENT_ID);
CREATE INDEX INCOMING_FILESET_ID_COURSE_STUDENT_ID_IDX ON GRAD_SAGA (INCOMING_FILESET_ID, COURSE_STUDENT_ID);

CREATE TABLE GRAD_SAGA_EVENT_STATES
(
    SAGA_EVENT_ID       UUID                                NOT NULL,
    SAGA_ID             UUID                                NOT NULL,
    SAGA_EVENT_STATE    VARCHAR(100)                        NOT NULL,
    SAGA_EVENT_OUTCOME  VARCHAR(100)                        NOT NULL,
    SAGA_STEP_NUMBER    INTEGER                             NOT NULL,
    SAGA_EVENT_RESPONSE VARCHAR                             NOT NULL,
    CREATE_USER         VARCHAR(32)                         NOT NULL,
    CREATE_DATE         TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATE_USER         VARCHAR(32)                         NOT NULL,
    UPDATE_DATE         TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT GRAD_SAGA_EVENT_STATES_PK PRIMARY KEY (SAGA_EVENT_ID)
);
ALTER TABLE GRAD_SAGA_EVENT_STATES
    ADD CONSTRAINT GRAD_SAGA_EVENT_STATES_SAGA_ID_FK FOREIGN KEY (SAGA_ID) REFERENCES GRAD_SAGA (SAGA_ID);
CREATE INDEX GRAD_SAGA_EVENT_STATES_SID_SES_SEO_SSN_IDX ON GRAD_SAGA_EVENT_STATES (SAGA_ID, SAGA_EVENT_STATE, SAGA_EVENT_OUTCOME, SAGA_STEP_NUMBER);
