CREATE TABLE ERROR_FILESET_STUDENT
(
    ERROR_FILESET_STUDENT_ID    UUID                                NOT NULL,
    INCOMING_FILESET_ID         UUID                                NOT NULL,
    PEN                         VARCHAR(10),
    CONSTRAINT ERROR_FILESET_STUDENT_ID_PK PRIMARY KEY (ERROR_FILESET_STUDENT_ID)
    CONSTRAINT ERROR_FILESET_STUDENT_INCOMING_FILESET_ID_FK FOREIGN KEY (INCOMING_FILESET_ID) REFERENCES INCOMING_FILESET (INCOMING_FILESET_ID)
    CONSTRAINT ERROR_FILESET_STUDENT_INCOMING_FILESET_ID_PEN_UK UNIQUE (INCOMING_FILESET_ID, PEN)
);