ALTER TABLE ASSESSMENT_STUDENT ADD COLUMN COURSE_LEVEL VARCHAR(3);
ALTER TABLE ASSESSMENT_STUDENT ADD COLUMN INTERIM_LETTER_GRADE VARCHAR(2);
ALTER TABLE ASSESSMENT_STUDENT ADD COLUMN INTERIM_SCHOOL_PERCENT VARCHAR(3);
ALTER TABLE ASSESSMENT_STUDENT ADD COLUMN FINAL_SCHOOL_PERCENT VARCHAR(3);
ALTER TABLE ASSESSMENT_STUDENT ADD COLUMN EXAM_PERCENT VARCHAR(3);
ALTER TABLE ASSESSMENT_STUDENT ADD COLUMN FINAL_PERCENT VARCHAR(3);
ALTER TABLE ASSESSMENT_STUDENT ADD COLUMN FINAL_LETTER_GRADE VARCHAR(2);
ALTER TABLE ASSESSMENT_STUDENT ADD COLUMN NUM_CREDITS VARCHAR(2);
ALTER TABLE ASSESSMENT_STUDENT ADD COLUMN CRSE_TYPE VARCHAR(1);
ALTER TABLE ASSESSMENT_STUDENT ADD COLUMN TO_WRITE_FLAG VARCHAR(1);

ALTER TABLE ASSESSMENT_STUDENT ALTER COLUMN PROVINCIAL_SPECIAL_CASE TYPE VARCHAR(1);
ALTER TABLE ASSESSMENT_STUDENT ALTER COLUMN COURSE_STATUS TYPE VARCHAR(1);
ALTER TABLE ASSESSMENT_STUDENT ALTER COLUMN LAST_NAME TYPE VARCHAR(25);

ALTER TABLE DEMOGRAPHIC_STUDENT ALTER COLUMN LAST_NAME TYPE VARCHAR(25);
ALTER TABLE DEMOGRAPHIC_STUDENT ALTER COLUMN FIRST_NAME TYPE VARCHAR(25);
ALTER TABLE DEMOGRAPHIC_STUDENT ALTER COLUMN MIDDLE_NAME TYPE VARCHAR(25);

ALTER TABLE DEMOGRAPHIC_STUDENT ALTER COLUMN ADDRESS1 TYPE VARCHAR(40);
ALTER TABLE DEMOGRAPHIC_STUDENT ALTER COLUMN ADDRESS2 TYPE VARCHAR(40);
ALTER TABLE DEMOGRAPHIC_STUDENT ALTER COLUMN CITY TYPE VARCHAR(30);
ALTER TABLE DEMOGRAPHIC_STUDENT ALTER COLUMN GRADE TYPE VARCHAR(2);

ALTER TABLE COURSE_STUDENT ALTER COLUMN LAST_NAME TYPE VARCHAR(25);
ALTER TABLE COURSE_STUDENT ALTER COLUMN COURSE_DESCRIPTION TYPE VARCHAR(40);

INSERT INTO STUDENT_STATUS_CODE (STUDENT_STATUS_CODE, LABEL, DESCRIPTION, DISPLAY_ORDER,
                                 CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
VALUES ('UPDATED', 'Updated', 'Student record has been updated downstream', '10',
        'API_GRAD_DATA_COLLECTION',
        TO_DATE('20241017', 'YYYYMMDD'),
        'API_GRAD_DATA_COLLECTION', TO_DATE('20241017', 'YYYYMMDD'));

INSERT INTO STUDENT_STATUS_CODE (STUDENT_STATUS_CODE, LABEL, DESCRIPTION, DISPLAY_ORDER,
                                 CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
VALUES ('VERIFIED', 'Verified', 'Student record has been updated downstream', '10',
        'API_GRAD_DATA_COLLECTION',
        TO_DATE('20241017', 'YYYYMMDD'),
        'API_GRAD_DATA_COLLECTION', TO_DATE('20241017', 'YYYYMMDD'));
