CREATE TABLE FINAL_INCOMING_FILESET (
   INCOMING_FILESET_ID UUID NOT NULL,
   SCHOOL_ID UUID NOT NULL,
   DEM_FILE_NAME VARCHAR(255) NULL,
   DEM_FILE_DATE_UPLOADED TIMESTAMP NULL,
   XAM_FILE_NAME VARCHAR(255) NULL,
   XAM_FILE_DATE_UPLOADED TIMESTAMP NULL,
   CRS_FILE_NAME VARCHAR(255) NULL,
   CRS_FILE_DATE_UPLOADED TIMESTAMP NULL,
   FILESET_STATUS_CODE VARCHAR(10) NOT NULL,
   CREATE_USER VARCHAR(100) NOT NULL,
   CREATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
   UPDATE_USER VARCHAR(100) NOT NULL,
   UPDATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
   DISTRICT_ID UUID NULL,
   REPORTING_PERIOD_ID UUID NOT NULL,
   CSV_FILE_NAME VARCHAR(255) NULL,
   CONSTRAINT INCOMING_FILESET_ID_PK PRIMARY KEY (INCOMING_FILESET_ID),
   CONSTRAINT FK_INCOMING_FILESET_FILESET_STATUS_CODE FOREIGN KEY (FILESET_STATUS_CODE) REFERENCES FILE_STATUS_CODE(FILE_STATUS_CODE),
   CONSTRAINT FK_REPORTING_PERIOD_ID FOREIGN KEY (REPORTING_PERIOD_ID) REFERENCES REPORTING_PERIOD(REPORTING_PERIOD_ID)
);
CREATE INDEX FINAL_FILESET_DISTRICT_ID_IDX ON FINAL_INCOMING_FILESET USING BTREE (DISTRICT_ID);
CREATE INDEX FINAL_FILESET_SCHOOL_ID_IDX ON FINAL_INCOMING_FILESET USING BTREE (SCHOOL_ID);
CREATE INDEX FINAL_FILESET_STATUS_CODE_IDX ON FINAL_INCOMING_FILESET USING BTREE (FILESET_STATUS_CODE);

CREATE TABLE FINAL_ASSESSMENT_STUDENT (
     ASSESSMENT_STUDENT_ID UUID NOT NULL,
     INCOMING_FILESET_ID UUID NOT NULL,
     STUDENT_STATUS_CODE VARCHAR(10) NOT NULL,
     LOCAL_ID VARCHAR(12) NULL,
     PEN VARCHAR(10) NULL,
     COURSE_CODE VARCHAR(5) NULL,
     COURSE_YEAR VARCHAR(4) NULL,
     COURSE_MONTH VARCHAR(2) NULL,
     IS_ELECTRONIC_EXAM VARCHAR(1) NULL,
     PROVINCIAL_SPECIAL_CASE VARCHAR(1) NULL,
     LOCAL_COURSE_ID VARCHAR(255) NULL,
     COURSE_STATUS VARCHAR(1) NULL,
     LAST_NAME VARCHAR(25) NULL,
     CREATE_USER VARCHAR(100) NOT NULL,
     CREATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
     UPDATE_USER VARCHAR(100) NOT NULL,
     UPDATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
     ASSESSMENT_ID UUID NULL,
     TRANSACTION_ID VARCHAR(3) NULL,
     COURSE_LEVEL VARCHAR(3) NULL,
     INTERIM_LETTER_GRADE VARCHAR(2) NULL,
     INTERIM_SCHOOL_PERCENT VARCHAR(3) NULL,
     FINAL_SCHOOL_PERCENT VARCHAR(3) NULL,
     EXAM_PERCENT VARCHAR(3) NULL,
     FINAL_PERCENT VARCHAR(3) NULL,
     FINAL_LETTER_GRADE VARCHAR(2) NULL,
     NUM_CREDITS VARCHAR(2) NULL,
     CRSE_TYPE VARCHAR(1) NULL,
     TO_WRITE_FLAG VARCHAR(1) NULL,
     EXAM_SCHOOL_ID UUID NULL,
     VENDOR_ID VARCHAR(1) NULL,
     CONSTRAINT FINAL_ASSESSMENT_STUDENT_ID_PK PRIMARY KEY (ASSESSMENT_STUDENT_ID),
     CONSTRAINT FK_FINAL_ASSESSMENT_STUDENT_FILE_STATUS_CODE FOREIGN KEY (STUDENT_STATUS_CODE) REFERENCES STUDENT_STATUS_CODE(STUDENT_STATUS_CODE),
     CONSTRAINT FK_FINAL_ASSESSMENT_STUDENT_INCOMING_FILESET_ID FOREIGN KEY (INCOMING_FILESET_ID) REFERENCES FINAL_INCOMING_FILESET(INCOMING_FILESET_ID) ON DELETE CASCADE
);
CREATE INDEX FINAL_ASSESSMENT_INCOMING_FILESET_ID_IDX ON FINAL_ASSESSMENT_STUDENT USING BTREE (INCOMING_FILESET_ID);
CREATE INDEX FINAL_ASSESSMENT_INCOMING_FILESET_ID_STUDENT_STATUS_IDX ON FINAL_ASSESSMENT_STUDENT USING BTREE (STUDENT_STATUS_CODE);

CREATE TABLE FINAL_ASSESSMENT_STUDENT_VALIDATION_ISSUE (
      ASSESSMENT_STUDENT_VALIDATION_ISSUE_ID UUID NOT NULL,
      ASSESSMENT_STUDENT_ID UUID NOT NULL,
      VALIDATION_ISSUE_SEVERITY_CODE VARCHAR(10) NOT NULL,
      VALIDATION_ISSUE_CODE VARCHAR(100) NOT NULL,
      VALIDATION_ISSUE_FIELD_CODE VARCHAR(100) NOT NULL,
      CREATE_USER VARCHAR(100) NOT NULL,
      CREATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
      UPDATE_USER VARCHAR(100) NOT NULL,
      UPDATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
      VALIDATION_ISSUE_DESCRIPTION VARCHAR(4000) NOT NULL,
      CONSTRAINT FINAL_ASSESSMENT_STUDENT_VALIDATION_ISSUE_ID_PK PRIMARY KEY (ASSESSMENT_STUDENT_VALIDATION_ISSUE_ID),
      CONSTRAINT FK_FINAL_ASSESSMENT_STUDENT_VALIDATION_CRS_FILE_STATUS_CODE FOREIGN KEY (ASSESSMENT_STUDENT_ID) REFERENCES FINAL_ASSESSMENT_STUDENT(ASSESSMENT_STUDENT_ID),
      CONSTRAINT FK_FINAL_ASSMT_STUD_VALID_ISSUE_ASSMT_STUD_ID FOREIGN KEY (ASSESSMENT_STUDENT_ID) REFERENCES FINAL_ASSESSMENT_STUDENT(ASSESSMENT_STUDENT_ID) ON DELETE CASCADE
);
CREATE INDEX FINAL_ASSESSMENT_STUDENT_ID_IDX ON FINAL_ASSESSMENT_STUDENT_VALIDATION_ISSUE USING BTREE (ASSESSMENT_STUDENT_ID);

CREATE TABLE FINAL_COURSE_STUDENT (
     COURSE_STUDENT_ID UUID NOT NULL,
     INCOMING_FILESET_ID UUID NOT NULL,
     STUDENT_STATUS_CODE VARCHAR(10) NOT NULL,
     LOCAL_ID VARCHAR(12) NULL,
     PEN VARCHAR(10) NULL,
     COURSE_CODE VARCHAR(5) NULL,
     COURSE_LEVEL VARCHAR(3) NULL,
     COURSE_YEAR VARCHAR(4) NULL,
     COURSE_MONTH VARCHAR(2) NULL,
     INTERIM_PERCENTAGE VARCHAR(3) NULL,
     INTERIM_GRADE VARCHAR(2) NULL,
     FINAL_PERCENTAGE VARCHAR(3) NULL,
     FINAL_GRADE VARCHAR(2) NULL,
     COURSE_STATUS VARCHAR(1) NULL,
     LAST_NAME VARCHAR(25) NULL,
     NUMBER_OF_CREDITS VARCHAR(2) NULL,
     RELATED_COURSE VARCHAR(5) NULL,
     RELATED_LEVEL VARCHAR(3) NULL,
     COURSE_DESCRIPTION VARCHAR(40) NULL,
     COURSE_TYPE VARCHAR(1) NULL,
     COURSE_GRADUATION_REQUIREMENT VARCHAR(1) NULL,
     CREATE_USER VARCHAR(100) NOT NULL,
     CREATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
     UPDATE_USER VARCHAR(100) NOT NULL,
     UPDATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
     TRANSACTION_ID VARCHAR(3) NULL,
     VENDOR_ID VARCHAR(1) NULL,
     CONSTRAINT FINAL_COURSE_STUDENT_ID_PK PRIMARY KEY (COURSE_STUDENT_ID),
     CONSTRAINT FK_FINAL_COURSE_STUDENT_CRS_FILE_STATUS_CODE FOREIGN KEY (STUDENT_STATUS_CODE) REFERENCES STUDENT_STATUS_CODE(STUDENT_STATUS_CODE),
     CONSTRAINT FK_FINAL_COURSE_STUDENT_INCOMING_FILESET_ID FOREIGN KEY (INCOMING_FILESET_ID) REFERENCES FINAL_INCOMING_FILESET(INCOMING_FILESET_ID) ON DELETE CASCADE
);
CREATE INDEX FINAL_CRS_INCOMING_FILESET_ID_IDX ON FINAL_COURSE_STUDENT USING BTREE (INCOMING_FILESET_ID);
CREATE INDEX FINAL_CRS_INCOMING_FILESET_ID_STUDENT_STATUS_IDX ON FINAL_COURSE_STUDENT USING BTREE (STUDENT_STATUS_CODE);

CREATE TABLE FINAL_COURSE_STUDENT_VALIDATION_ISSUE (
      COURSE_STUDENT_VALIDATION_ISSUE_ID UUID NOT NULL,
      COURSE_STUDENT_ID UUID NOT NULL,
      VALIDATION_ISSUE_SEVERITY_CODE VARCHAR(10) NOT NULL,
      VALIDATION_ISSUE_CODE VARCHAR(100) NOT NULL,
      VALIDATION_ISSUE_FIELD_CODE VARCHAR(100) NOT NULL,
      CREATE_USER VARCHAR(100) NOT NULL,
      CREATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
      UPDATE_USER VARCHAR(100) NOT NULL,
      UPDATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
      VALIDATION_ISSUE_DESCRIPTION VARCHAR(4000) NOT NULL,
      CONSTRAINT FINAL_COURSE_STUDENT_VALIDATION_ISSUE_ID_PK PRIMARY KEY (COURSE_STUDENT_VALIDATION_ISSUE_ID),
      CONSTRAINT FK_FINAL_COURSE_STUD_VALID_ISSUE_COURSE_STUD_ID FOREIGN KEY (COURSE_STUDENT_ID) REFERENCES FINAL_COURSE_STUDENT(COURSE_STUDENT_ID) ON DELETE CASCADE,
      CONSTRAINT FK_FINAL_COURSE_STUDENT_VALIDATION_CRS_FILE_STATUS_CODE FOREIGN KEY (COURSE_STUDENT_ID) REFERENCES FINAL_COURSE_STUDENT(COURSE_STUDENT_ID)
);
CREATE INDEX FINAL_COURSE_STUDENT_ID_IDX ON COURSE_STUDENT_VALIDATION_ISSUE USING BTREE (COURSE_STUDENT_ID);

CREATE TABLE FINAL_DEMOGRAPHIC_STUDENT (
      DEMOGRAPHIC_STUDENT_ID UUID NOT NULL,
      INCOMING_FILESET_ID UUID NOT NULL,
      STUDENT_STATUS_CODE VARCHAR(10) NOT NULL,
      LOCAL_ID VARCHAR(12) NULL,
      PEN VARCHAR(10) NULL,
      LAST_NAME VARCHAR(25) NULL,
      FIRST_NAME VARCHAR(25) NULL,
      ADDRESS1 VARCHAR(40) NULL,
      ADDRESS2 VARCHAR(40) NULL,
      CITY VARCHAR(30) NULL,
      PROVINCIAL_CODE VARCHAR(2) NULL,
      COUNTRY_CODE VARCHAR(3) NULL,
      POSTAL_CODE VARCHAR(7) NULL,
      BIRTHDATE VARCHAR(8) NULL,
      GENDER VARCHAR(1) NULL,
      CITIZENSHIP VARCHAR(1) NULL,
      GRADE VARCHAR(2) NULL,
      PROGRAM_CODE_1 VARCHAR(4) NULL,
      PROGRAM_CODE_2 VARCHAR(4) NULL,
      PROGRAM_CODE_3 VARCHAR(4) NULL,
      PROGRAM_CODE_4 VARCHAR(4) NULL,
      PROGRAM_CODE_5 VARCHAR(4) NULL,
      PROGRAM_CADRE_FLAG VARCHAR(1) NULL,
      GRAD_REQUIREMENT_YEAR VARCHAR(4) NULL,
      SCHOOL_CERTIFICATE_COMPLETION_DATE VARCHAR(8) NULL,
      CREATE_USER VARCHAR(100) NOT NULL,
      CREATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
      UPDATE_USER VARCHAR(100) NOT NULL,
      UPDATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
      TRANSACTION_ID VARCHAR(3) NULL,
      MIDDLE_NAME VARCHAR(25) NULL,
      STUDENT_STATUS VARCHAR(1) NULL,
      VENDOR_ID VARCHAR(1) NULL,
      CONSTRAINT FINAL_DEMOGRAPHIC_STUDENT_ID_PK PRIMARY KEY (DEMOGRAPHIC_STUDENT_ID),
      CONSTRAINT FK_FINAL_DEMOGRAPHIC_STUDENT_FILE_STATUS_CODE FOREIGN KEY (STUDENT_STATUS_CODE) REFERENCES STUDENT_STATUS_CODE(STUDENT_STATUS_CODE),
      CONSTRAINT FK_FINAL_DEMOGRAPHIC_STUDENT_INCOMING_FILESET_ID FOREIGN KEY (INCOMING_FILESET_ID) REFERENCES FINAL_INCOMING_FILESET(INCOMING_FILESET_ID) ON DELETE CASCADE
);
CREATE INDEX FINAL_DEM_INCOMING_FILESET_ID_IDX ON FINAL_DEMOGRAPHIC_STUDENT USING BTREE (INCOMING_FILESET_ID);
CREATE INDEX FINAL_DEM_INCOMING_FILESET_ID_STUDENT_STATUS_IDX ON FINAL_DEMOGRAPHIC_STUDENT USING BTREE (STUDENT_STATUS_CODE);

CREATE TABLE FINAL_DEMOGRAPHIC_STUDENT_VALIDATION_ISSUE (
       DEMOGRAPHIC_STUDENT_VALIDATION_ISSUE_ID UUID NOT NULL,
       DEMOGRAPHIC_STUDENT_ID UUID NOT NULL,
       VALIDATION_ISSUE_SEVERITY_CODE VARCHAR(10) NOT NULL,
       VALIDATION_ISSUE_CODE VARCHAR(100) NOT NULL,
       VALIDATION_ISSUE_FIELD_CODE VARCHAR(100) NOT NULL,
       CREATE_USER VARCHAR(100) NOT NULL,
       CREATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
       UPDATE_USER VARCHAR(100) NOT NULL,
       UPDATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
       VALIDATION_ISSUE_DESCRIPTION VARCHAR(4000) NOT NULL,
       CONSTRAINT FINAL_DEMOGRAPHIC_STUDENT_VALIDATION_ISSUE_ID_PK PRIMARY KEY (DEMOGRAPHIC_STUDENT_VALIDATION_ISSUE_ID),
       CONSTRAINT FK_FINAL_DEM_STUD_VALID_ISSUE_DEM_STUD_ID FOREIGN KEY (DEMOGRAPHIC_STUDENT_ID) REFERENCES FINAL_DEMOGRAPHIC_STUDENT(DEMOGRAPHIC_STUDENT_ID) ON DELETE CASCADE,
       CONSTRAINT FK_FINAL_DEMOGRAPHIC_STUDENT_VALIDATION_CRS_FILE_STATUS_CODE FOREIGN KEY (DEMOGRAPHIC_STUDENT_ID) REFERENCES FINAL_DEMOGRAPHIC_STUDENT(DEMOGRAPHIC_STUDENT_ID)
);
CREATE INDEX FINAL_DEMOGRAPHIC_STUDENT_ID_IDX ON FINAL_DEMOGRAPHIC_STUDENT_VALIDATION_ISSUE USING BTREE (DEMOGRAPHIC_STUDENT_ID);

CREATE TABLE FINAL_ERROR_FILESET_STUDENT (
        ERROR_FILESET_STUDENT_ID UUID NOT NULL,
        INCOMING_FILESET_ID UUID NOT NULL,
        PEN VARCHAR(10) NOT NULL,
        LOCAL_ID VARCHAR(12) NULL,
        FIRST_NAME VARCHAR(25) NULL,
        LAST_NAME VARCHAR(25) NULL,
        BIRTHDATE VARCHAR(8) NULL,
        CREATE_USER VARCHAR(100) NOT NULL,
        CREATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
        UPDATE_USER VARCHAR(100) NOT NULL,
        UPDATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
        CONSTRAINT FINAL_ERROR_FILESET_STUDENT_ID_PK PRIMARY KEY (ERROR_FILESET_STUDENT_ID),
        CONSTRAINT FINAL_ERROR_FILESET_STUDENT_INCOMING_FILESET_ID_PEN_UK UNIQUE (INCOMING_FILESET_ID, PEN),
        CONSTRAINT FK_FINAL_ERROR_FILESET_STUDENT_INCOMING_FILESET_ID FOREIGN KEY (INCOMING_FILESET_ID) REFERENCES FINAL_INCOMING_FILESET(INCOMING_FILESET_ID) ON DELETE CASCADE
);