ALTER TABLE ERROR_FILESET_STUDENT ADD COLUMN BIRTHDATE VARCHAR(8);
ALTER TABLE ERROR_FILESET_STUDENT ALTER COLUMN LOCAL_ID DROP NOT NULL;
ALTER TABLE ERROR_FILESET_STUDENT ALTER COLUMN FIRST_NAME DROP NOT NULL;
ALTER TABLE ERROR_FILESET_STUDENT ALTER COLUMN LAST_NAME DROP NOT NULL;
