ALTER TABLE ERROR_FILESET_STUDENT
    ADD COLUMN CREATE_USER VARCHAR(100) DEFAULT 'API_GRAD_DATA_COLLECTION' NOT NULL,
    ADD COLUMN CREATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    ADD COLUMN UPDATE_USER VARCHAR(100) DEFAULT 'API_GRAD_DATA_COLLECTION' NOT NULL,
    ADD COLUMN UPDATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL;

ALTER TABLE ERROR_FILESET_STUDENT
    ALTER COLUMN CREATE_USER DROP DEFAULT,
    ALTER COLUMN UPDATE_USER DROP DEFAULT;