alter table GRAD_SAGA_EVENT_STATES DROP CONSTRAINT GRAD_SAGA_EVENT_STATES_SAGA_ID_FK;
ALTER TABLE GRAD_SAGA_EVENT_STATES ADD CONSTRAINT GRAD_SAGA_EVENT_STATES_SAGA_ID_FK FOREIGN KEY (SAGA_ID) REFERENCES GRAD_SAGA(SAGA_ID) on delete cascade;
