package ca.bc.gov.educ.graddatacollection.api.constants;

/**
 * The enum Event type.
 */
public enum EventType {
  INITIATED,
  MARK_SAGA_COMPLETE,
  GET_PAGINATED_SCHOOLS,
  GET_STUDENT,
  GET_GRAD_STUDENT_RECORD,
  GET_STUDENT_ASSESSMENT_DETAILS,
  GET_OPEN_ASSESSMENT_SESSIONS,
  READ_DEM_STUDENTS_FOR_PROCESSING,
  READ_ASSESSMENT_STUDENTS_FOR_PROCESSING,
  READ_COURSE_STUDENTS_FOR_PROCESSING,
  VALIDATE_DEM_STUDENT,
  CREATE_DEM_STUDENT_IN_GRAD,
  VALIDATE_COURSE_STUDENT,
  CREATE_COURSE_STUDENT_IN_GRAD,
  UPDATE_COURSE_STUDENT_STATUS_IN_COLLECTION,
  VALIDATE_ASSESSMENT_STUDENT,
  CREATE_ASSESSMENT_STUDENT_IN_GRAD,
  UPDATE_ASSESSMENT_STUDENT_STATUS_IN_COLLECTION,
  UPDATE_DEM_STUDENT_STATUS_IN_COLLECTION,
  GET_COURSE_FROM_EXTERNAL_ID,
  GET_STUDENT_COURSE
}
