package ca.bc.gov.educ.graddatacollection.api.constants;

/**
 * The enum Event outcome.
 */
public enum EventOutcome {
  INITIATE_SUCCESS,
  SAGA_COMPLETED,
  READ_DEM_STUDENTS_FOR_PROCESSING_SUCCESS,
  READ_ASSESSMENT_STUDENTS_FOR_PROCESSING_SUCCESS,
  READ_COURSE_STUDENTS_FOR_PROCESSING_SUCCESS,
  VALIDATE_DEM_STUDENT_SUCCESS_WITH_NO_ERROR,
  VALIDATE_DEM_STUDENT_SUCCESS_WITH_ERROR,
  DEM_STUDENT_CREATED_IN_GRAD,
  DEM_STUDENT_STATUS_IN_COLLECTION_UPDATED
}
