package ca.bc.gov.educ.graddatacollection.api.constants;

public enum SagaEnum {
    PROCESS_COMPLETED_FILESETS_SAGA,
    PROCESS_DEM_STUDENTS_SAGA,
    PROCESS_COURSE_STUDENTS_SAGA,
    PROCESS_ASSESSMENT_STUDENTS_SAGA,
    PROCESS_COURSE_STUDENTS_FOR_DOWNSTREAM_UPDATE_SAGA

}
