package ca.bc.gov.educ.graddatacollection.api.constants;


public enum TopicsEnum {
  INSTITUTE_API_TOPIC,
  STUDENT_API_TOPIC,
  GRAD_EVENTS_TOPIC,
  EAS_API_TOPIC,
  READ_DEM_STUDENTS_FROM_TOPIC,
  READ_ASSESSMENT_STUDENTS_FROM_TOPIC,
  READ_COURSE_STUDENTS_FROM_TOPIC,
  PROCESS_DEM_STUDENTS_SAGA_TOPIC,
  PROCESS_COURSE_STUDENTS_SAGA_TOPIC

}
