package ca.bc.gov.educ.graddatacollection.api.constants;


public enum TopicsEnum {
  INSTITUTE_API_TOPIC,
  STUDENT_API_TOPIC,
  GDC_EVENTS_TOPIC,
  GRAD_STUDENT_API_FETCH_GRAD_STUDENT_TOPIC,
  GRAD_STUDENT_API_FETCH_GRAD_STUDENT_COURSES_TOPIC,
  STUDENT_ASSESSMENT_API_TOPIC,
  READ_DEM_STUDENTS_FROM_TOPIC,
  READ_ASSESSMENT_STUDENTS_FROM_TOPIC,
  READ_COURSE_STUDENTS_FROM_TOPIC,
  PROCESS_DEM_STUDENTS_SAGA_TOPIC,
  PROCESS_COURSE_STUDENTS_SAGA_TOPIC,
  PROCESS_ASSESSMENT_STUDENTS_SAGA_TOPIC,
  COREG_API_TOPIC,
  GRAD_COURSE_API_TOPIC,
  GRAD_SCHOOL_EVENTS_TOPIC,
  GRAD_STUDENT_API_TOPIC,
  READ_COURSE_STUDENTS_FOR_DOWNSTREAM_UPDATE_TOPIC,
  PROCESS_COURSE_STUDENTS_SAGA_FOR_DOWNSTREAM_UPDATE_TOPIC,
  READ_COMPLETED_FILESETS_FROM_TOPIC,
  PROCESS_COMPLETED_FILESETS_SAGA_TOPIC
}
